import type {
  User,
  Post,
  Session,
  MatchRequest,
  Notification,
} from "./types";

export const currentUser: User = {
  id: "u1",
  name: "Alex Chen",
  email: "alex.chen@uni.minerva.edu",
  timezone: "America/Los_Angeles",
  bio: "CS senior focusing on systems design and backend engineering. Preparing for SWE roles at FAANG companies.",
  role: "both",
  interviewTypes: ["technical", "behavioral"],
  topics: ["Data Structures", "System Design", "Dynamic Programming"],
  experienceLevel: "intermediate",
  completedSessions: 12,
  rating: 4.8,
  joinedAt: "2025-09-15",
  schedulingUrl: "https://calendly.com/alexchen",
};

export const users: User[] = [
  currentUser,
  {
    id: "u2",
    name: "Priya Sharma",
    email: "priya.sharma@uni.minerva.edu",
    timezone: "Asia/Kolkata",
    bio: "Product management aspirant with experience in user research and analytics.",
    role: "interviewer",
    interviewTypes: ["product", "behavioral"],
    topics: ["Product Sense", "Metrics", "Strategy"],
    experienceLevel: "advanced",
    completedSessions: 24,
    rating: 4.9,
    joinedAt: "2025-08-01",
    schedulingUrl: "https://calendly.com/priyasharma",
  },
  {
    id: "u3",
    name: "Marcus Johnson",
    email: "marcus.j@uni.minerva.edu",
    timezone: "America/New_York",
    bio: "Former consultant preparing for tech PM roles. Strong in case interviews and structured thinking.",
    role: "interviewer",
    interviewTypes: ["case", "product", "behavioral"],
    topics: ["Market Sizing", "Profitability", "Go-to-Market"],
    experienceLevel: "advanced",
    completedSessions: 31,
    rating: 4.7,
    joinedAt: "2025-07-20",
    schedulingUrl: "https://cal.com/marcusjohnson",
  },
  {
    id: "u4",
    name: "Yuki Tanaka",
    email: "yuki.t@uni.minerva.edu",
    timezone: "Asia/Tokyo",
    bio: "ML engineer preparing for research-focused roles. Love discussing system design and ML infra.",
    role: "both",
    interviewTypes: ["technical"],
    topics: ["Machine Learning", "System Design", "Python", "Statistics"],
    experienceLevel: "intermediate",
    completedSessions: 8,
    rating: 4.6,
    joinedAt: "2025-10-01",
    schedulingUrl: "https://calendly.com/yukitanaka",
  },
  {
    id: "u5",
    name: "Sofia Rodriguez",
    email: "sofia.r@uni.minerva.edu",
    timezone: "Europe/Berlin",
    bio: "Full-stack developer interested in startup engineering roles. Enjoys pair programming and code reviews.",
    role: "interviewee",
    interviewTypes: ["technical", "behavioral"],
    topics: ["React", "Node.js", "System Design", "API Design"],
    experienceLevel: "intermediate",
    completedSessions: 15,
    rating: 4.8,
    joinedAt: "2025-09-01",
  },
  {
    id: "u6",
    name: "Daniel Kim",
    email: "daniel.k@uni.minerva.edu",
    timezone: "America/Los_Angeles",
    bio: "Aspiring quant preparing for trading firm interviews. Strong math and algorithms background.",
    role: "both",
    interviewTypes: ["technical", "case"],
    topics: ["Algorithms", "Probability", "Brain Teasers", "Dynamic Programming"],
    experienceLevel: "advanced",
    completedSessions: 19,
    rating: 4.9,
    joinedAt: "2025-08-15",
    schedulingUrl: "https://cal.com/danielkim",
  },
];

export const posts: Post[] = [
  {
    id: "p1",
    author: users[1],
    intent: "give",
    interviewType: "product",
    topics: ["Product Sense", "Metrics"],
    difficulty: "intermediate",
    duration: 45,
    targetCompany: "Google",
    description:
      "I've done 20+ PM interviews and can simulate Google APM-style product sense questions. Happy to give detailed feedback on frameworks and communication.",
    availabilitySlots: [
      { id: "s1", date: "2026-02-23", startTime: "10:00", endTime: "11:00" },
      { id: "s2", date: "2026-02-24", startTime: "14:00", endTime: "15:00" },
      { id: "s3", date: "2026-02-25", startTime: "09:00", endTime: "10:00" },
    ],
    createdAt: "2026-02-20T08:30:00Z",
    status: "open",
  },
  {
    id: "p2",
    author: users[2],
    intent: "give",
    interviewType: "case",
    topics: ["Market Sizing", "Profitability"],
    difficulty: "advanced",
    duration: 60,
    targetCompany: "McKinsey",
    description:
      "Ex-consulting background. I'll run a full MBB-style case with you including market sizing, profitability analysis, and synthesis. Expect real feedback.",
    availabilitySlots: [
      { id: "s4", date: "2026-02-22", startTime: "16:00", endTime: "17:00" },
      { id: "s5", date: "2026-02-23", startTime: "11:00", endTime: "12:00" },
    ],
    createdAt: "2026-02-19T15:00:00Z",
    status: "open",
  },
  {
    id: "p3",
    author: users[3],
    intent: "both",
    interviewType: "technical",
    topics: ["Machine Learning", "System Design"],
    difficulty: "intermediate",
    duration: 60,
    description:
      "Looking to practice ML system design (recommendation systems, search ranking, etc). Happy to swap roles — I can also interview you on general system design.",
    availabilitySlots: [
      { id: "s6", date: "2026-02-23", startTime: "08:00", endTime: "09:00" },
      { id: "s7", date: "2026-02-24", startTime: "08:00", endTime: "09:00" },
      { id: "s8", date: "2026-02-26", startTime: "19:00", endTime: "20:00" },
    ],
    createdAt: "2026-02-20T12:00:00Z",
    status: "open",
  },
  {
    id: "p4",
    author: users[4],
    intent: "get",
    interviewType: "technical",
    topics: ["React", "System Design", "API Design"],
    difficulty: "intermediate",
    duration: 45,
    targetCompany: "Stripe",
    description:
      "Preparing for Stripe frontend + full-stack interviews. Need someone to run me through system design and React architecture questions.",
    availabilitySlots: [
      { id: "s9", date: "2026-02-22", startTime: "18:00", endTime: "19:00" },
      {
        id: "s10",
        date: "2026-02-24",
        startTime: "10:00",
        endTime: "11:00",
      },
    ],
    createdAt: "2026-02-21T09:00:00Z",
    status: "open",
  },
  {
    id: "p5",
    author: users[5],
    intent: "both",
    interviewType: "technical",
    topics: ["Algorithms", "Dynamic Programming", "Data Structures"],
    difficulty: "advanced",
    duration: 60,
    targetCompany: "Jane Street",
    description:
      "Quant-style technical interviews — algorithms with a math twist. Looking for someone strong in DP and combinatorics to trade rounds with.",
    availabilitySlots: [
      {
        id: "s11",
        date: "2026-02-23",
        startTime: "15:00",
        endTime: "16:00",
      },
      {
        id: "s12",
        date: "2026-02-25",
        startTime: "13:00",
        endTime: "14:00",
      },
    ],
    createdAt: "2026-02-20T18:00:00Z",
    status: "open",
  },
  {
    id: "p6",
    author: users[1],
    intent: "get",
    interviewType: "behavioral",
    topics: ["Leadership", "Conflict Resolution", "Strategy"],
    difficulty: "intermediate",
    duration: 30,
    targetCompany: "Meta",
    description:
      "Need practice with Meta's behavioral questions — especially around leadership and navigating ambiguity. Looking for someone who can give structured feedback.",
    availabilitySlots: [
      {
        id: "s13",
        date: "2026-02-24",
        startTime: "16:00",
        endTime: "16:30",
      },
      {
        id: "s14",
        date: "2026-02-26",
        startTime: "11:00",
        endTime: "11:30",
      },
    ],
    createdAt: "2026-02-21T06:00:00Z",
    status: "open",
  },
];

export const sessions: Session[] = [
  {
    id: "ses1",
    interviewee: currentUser,
    interviewer: users[1],
    interviewType: "product",
    topics: ["Product Sense", "Metrics"],
    difficulty: "intermediate",
    duration: 45,
    scheduledAt: "2026-02-23T10:00:00Z",
    meetingLink: "https://meet.google.com/abc-defg-hij",
    status: "confirmed",
  },
  {
    id: "ses2",
    interviewee: users[4],
    interviewer: currentUser,
    interviewType: "technical",
    topics: ["System Design", "React"],
    difficulty: "intermediate",
    duration: 45,
    scheduledAt: "2026-02-24T18:00:00Z",
    meetingLink: "https://meet.google.com/klm-nopq-rst",
    status: "confirmed",
  },
  {
    id: "ses3",
    interviewee: currentUser,
    interviewer: users[5],
    interviewType: "technical",
    topics: ["Algorithms", "Dynamic Programming"],
    difficulty: "advanced",
    duration: 60,
    scheduledAt: "2026-02-18T15:00:00Z",
    meetingLink: "https://meet.google.com/uvw-xyza-bcd",
    status: "completed",
    feedback: {
      id: "f1",
      sessionId: "ses3",
      fromUser: users[5],
      toUser: currentUser,
      rating: 4,
      communication: 5,
      preparedness: 4,
      technicalSkill: 4,
      notes:
        "Great session! Alex showed strong problem-solving skills on the DP problem. Could improve on identifying optimal substructure faster.",
      strengths: "Clear communication, good at breaking down problems step by step",
      improvements: "Practice recognizing DP patterns more quickly. Consider edge cases earlier in the process.",
      createdAt: "2026-02-18T16:15:00Z",
    },
  },
  {
    id: "ses4",
    interviewee: users[2],
    interviewer: currentUser,
    interviewType: "behavioral",
    topics: ["Leadership", "Teamwork"],
    difficulty: "intermediate",
    duration: 30,
    scheduledAt: "2026-02-15T11:00:00Z",
    meetingLink: "https://meet.google.com/efg-hijk-lmn",
    status: "completed",
  },
];

export const matchRequests: MatchRequest[] = [
  {
    id: "mr1",
    post: posts[0],
    requester: currentUser,
    proposedSlots: [posts[0].availabilitySlots[0]],
    message:
      "Hi Priya! I'm preparing for Google and would love to practice product sense with you. I've been working through product frameworks and could use feedback on my structured thinking.",
    status: "pending",
    createdAt: "2026-02-21T10:00:00Z",
  },
  {
    id: "mr2",
    post: posts[3],
    requester: users[4],
    proposedSlots: [posts[3].availabilitySlots[0]],
    message:
      "Hey Alex, saw you're strong in system design. Would you be open to running a Stripe-style frontend system design question? I can share some prep materials in advance.",
    status: "pending",
    createdAt: "2026-02-21T09:30:00Z",
  },
];

export const notifications: Notification[] = [
  {
    id: "n1",
    type: "match_request",
    title: "New match request",
    message: "Sofia Rodriguez wants to practice with you",
    read: false,
    createdAt: "2026-02-21T09:30:00Z",
    actionUrl: "/requests",
  },
  {
    id: "n2",
    type: "session_reminder",
    title: "Session tomorrow",
    message: "Product Sense mock with Priya Sharma at 10:00 AM",
    read: false,
    createdAt: "2026-02-22T08:00:00Z",
    actionUrl: "/sessions/ses1",
  },
  {
    id: "n3",
    type: "feedback_received",
    title: "Feedback received",
    message: "Daniel Kim left feedback on your session",
    read: true,
    createdAt: "2026-02-18T16:15:00Z",
    actionUrl: "/sessions/ses3",
  },
  {
    id: "n4",
    type: "match_accepted",
    title: "Match confirmed",
    message: "Your session with Priya Sharma is confirmed",
    read: true,
    createdAt: "2026-02-20T14:00:00Z",
    actionUrl: "/sessions/ses1",
  },
];
