import type {
  User,
  Session,
} from "./types";

export const currentUser: User = {
  id: "u1",
  name: "Alex Chen",
  email: "alex.chen@uni.minerva.edu",
  timezone: "America/Los_Angeles",
  bio: "CS senior focusing on systems design and backend engineering. Preparing for SWE roles at FAANG companies.",
  role: "both",
  interviewTypes: ["technical", "behavioral"],
  topics: ["Data Structures", "System Design", "Dynamic Programming"],
  experienceLevel: "intermediate",
  completedSessions: 12,
  joinedAt: "2025-09-15",
  schedulingUrl: "https://calendly.com/alexchen",
};

export const users: User[] = [
  currentUser,
  {
    id: "u2",
    name: "Priya Sharma",
    email: "priya.sharma@uni.minerva.edu",
    timezone: "Asia/Kolkata",
    bio: "Product management aspirant with experience in user research and analytics.",
    role: "interviewer",
    interviewTypes: ["product", "behavioral"],
    topics: ["Product Sense", "Metrics", "Strategy"],
    experienceLevel: "advanced",
    completedSessions: 24,
    joinedAt: "2025-08-01",
    schedulingUrl: "https://calendly.com/priyasharma",
  },
  {
    id: "u3",
    name: "Marcus Johnson",
    email: "marcus.j@uni.minerva.edu",
    timezone: "America/New_York",
    bio: "Former consultant preparing for tech PM roles. Strong in case interviews and structured thinking.",
    role: "interviewer",
    interviewTypes: ["case", "product", "behavioral"],
    topics: ["Market Sizing", "Profitability", "Go-to-Market"],
    experienceLevel: "advanced",
    completedSessions: 31,
    joinedAt: "2025-07-20",
    schedulingUrl: "https://cal.com/marcusjohnson",
  },
  {
    id: "u4",
    name: "Yuki Tanaka",
    email: "yuki.t@uni.minerva.edu",
    timezone: "Asia/Tokyo",
    bio: "ML engineer preparing for research-focused roles. Love discussing system design and ML infra.",
    role: "both",
    interviewTypes: ["technical"],
    topics: ["Machine Learning", "System Design", "Python", "Statistics"],
    experienceLevel: "intermediate",
    completedSessions: 8,
    joinedAt: "2025-10-01",
    schedulingUrl: "https://calendly.com/yukitanaka",
  },
  {
    id: "u5",
    name: "Sofia Rodriguez",
    email: "sofia.r@uni.minerva.edu",
    timezone: "Europe/Berlin",
    bio: "Full-stack developer interested in startup engineering roles. Enjoys pair programming and code reviews.",
    role: "interviewee",
    interviewTypes: ["technical", "behavioral"],
    topics: ["React", "Node.js", "System Design", "API Design"],
    experienceLevel: "intermediate",
    completedSessions: 15,
    joinedAt: "2025-09-01",
  },
  {
    id: "u6",
    name: "Daniel Kim",
    email: "daniel.k@uni.minerva.edu",
    timezone: "America/Los_Angeles",
    bio: "Aspiring quant preparing for trading firm interviews. Strong math and algorithms background.",
    role: "both",
    interviewTypes: ["technical", "case"],
    topics: ["Algorithms", "Probability", "Brain Teasers", "Dynamic Programming"],
    experienceLevel: "advanced",
    completedSessions: 19,
    joinedAt: "2025-08-15",
    schedulingUrl: "https://cal.com/danielkim",
  },
];

export const sessions: Session[] = [
  {
    id: "ses1",
    interviewee: currentUser,
    interviewer: users[1],
    interviewType: "product",
    topics: ["Product Sense", "Metrics"],
    difficulty: "intermediate",
    duration: 45,
    scheduledAt: "2026-02-23T10:00:00Z",
    meetingLink: "https://meet.google.com/abc-defg-hij",
    status: "confirmed",
  },
  {
    id: "ses2",
    interviewee: users[4],
    interviewer: currentUser,
    interviewType: "technical",
    topics: ["System Design", "React"],
    difficulty: "intermediate",
    duration: 45,
    scheduledAt: "2026-02-24T18:00:00Z",
    meetingLink: "https://meet.google.com/klm-nopq-rst",
    status: "confirmed",
  },
  {
    id: "ses3",
    interviewee: currentUser,
    interviewer: users[5],
    interviewType: "technical",
    topics: ["Algorithms", "Dynamic Programming"],
    difficulty: "advanced",
    duration: 60,
    scheduledAt: "2026-02-18T15:00:00Z",
    meetingLink: "https://meet.google.com/uvw-xyza-bcd",
    status: "completed",
    feedback: {
      id: "f1",
      sessionId: "ses3",
      fromUser: users[5],
      toUser: currentUser,
      communication: 5,
      preparedness: 4,
      technicalSkill: 4,
      notes:
        "Great session! Alex showed strong problem-solving skills on the DP problem. Could improve on identifying optimal substructure faster.",
      strengths: "Clear communication, good at breaking down problems step by step",
      improvements: "Practice recognizing DP patterns more quickly. Consider edge cases earlier in the process.",
      createdAt: "2026-02-18T16:15:00Z",
    },
  },
  {
    id: "ses4",
    interviewee: users[2],
    interviewer: currentUser,
    interviewType: "behavioral",
    topics: ["Leadership", "Teamwork"],
    difficulty: "intermediate",
    duration: 30,
    scheduledAt: "2026-02-15T11:00:00Z",
    meetingLink: "https://meet.google.com/efg-hijk-lmn",
    status: "completed",
  },
];
